<?php
// src/locale/en.php
return [
    // edit_employee.php
    'work_information' => 'Work Information',
    'employee_id' => 'Employee ID',
    'job_title' => 'Job Title',
    'contract_role' => 'Contract Role',
    'department_s' => 'Department(s)',
    'add_department' => '+ Add Department...',
    'section_s' => 'Section(s)',
    'employment_type' => 'Employment Type',
    'hire_date' => 'Hire Date',
    'company_name' => 'Company Name',
    'previous_company' => 'Previous Company',
    'current_status' => 'Current Status',
    'active' => 'Active',
    'resigned' => 'Resigned',
    'terminated' => 'Terminated',
    'awol' => 'AWOL',
    'retired' => 'Retired',
    'date_of_exit' => 'Date of Exit',
    'reason_for_leaving' => 'Reason for Leaving',
    'personal_details' => 'Personal Details',
    'first_name' => 'First Name',
    'middle_name' => 'Middle Name',
    'last_name' => 'Last Name',
    'gender' => 'Gender',
    'male' => 'Male',
    'female' => 'Female',
    'birth_date' => 'Birth Date',
    'contact_number' => 'Contact Number',
    'email' => 'Email',
    'present_address' => 'Present Address',
    'permanent_address' => 'Permanent Address',
    'change_photo' => 'Change Photo',
    'remove_photo' => 'Remove Photo',
    'take_photo' => 'Take Photo',
    'government_ids' => 'Government IDs',
    'sss_no' => 'SSS No',
    'tin_no' => 'TIN No',
    'philhealth' => 'PhilHealth',
    'pagibig' => 'Pag-IBIG',
    'emergency_contact' => 'Emergency Contact',
    'name' => 'Name',
    'contact_no' => 'Contact No',
    'address' => 'Address',
    'qualifications_education' => 'Qualifications & Educational Background',
    'save_changes' => 'Save Changes',
    'cancel' => 'Cancel',
];
