<?php
// ======================================================
// [FILE] public/export_employees.php
// [PURPOSE] Executive-Grade CSV/Excel Export Engine
// ======================================================

require '../config/db.php';
require '../src/Logger.php';
require '../src/Validator.php';
session_start();

// 1. SECURITY CHECK
if (!isset($_SESSION['user_id'])) {
    die("Access Denied");
}

$requestedSensitive = isset($_GET['exportSensitive']) && $_GET['exportSensitive'] === 'true';
$hasSensitivePermission = in_array(strtoupper(trim($_SESSION['role'] ?? '')), ['ADMIN', 'HR'], true);
$includeSensitive = $hasSensitivePermission && $requestedSensitive;

// Audit log for export requests
$logger = new Logger($pdo);
$logger->log(
    $_SESSION['user_id'],
    'EXPORT_EMPLOYEES',
    'Export requested; includeSensitive=' . ($requestedSensitive ? 'true' : 'false') . ', allowed=' . ($hasSensitivePermission ? 'true' : 'false')
);

function maskSensitive($value, $unmasked = 4)
{
    if (!is_string($value) || $value === '') {
        return '';
    }
    $digits = preg_replace('/\D+/', '', $value);
    $len = strlen($digits);
    if ($len <= $unmasked) {
        return str_repeat('*', $len);
    }
    $visible = substr($digits, -1 * $unmasked);
    return str_repeat('*', $len - $unmasked) . $visible;
}

/**
 * Clean multi-line text fields for Excel CSV rendering
 */
function sanitizeExcelField($text)
{
    if ($text === null || $text === '') return '';
    // Replace carriage returns / newlines with space to preserve row integrity
    $clean = str_replace(["\r\n", "\r", "\n"], " | ", $text);
    return trim($clean);
}

/**
 * Force Excel to display long numbers/IDs as explicit text strings (prevents 4.26E+18)
 */
function forceExcelText($value)
{
    if ($value === null || $value === '') return '';
    // Prefixing with ="..." forces Excel to parse the column value strictly as string
    return '="' . str_replace('"', '""', $value) . '"';
}

// 2. GET FILTERS
$filter_status = isset($_GET['status']) ? trim($_GET['status']) : '';
$filter_type   = isset($_GET['type'])   ? trim($_GET['type'])   : '';
$filter_dept   = isset($_GET['dept'])   ? trim($_GET['dept'])   : '';
$search_query  = Validator::sanitizeSearch($_GET['search'] ?? '');

// 3. BUILD QUERY
$where = ['1=1'];
$params = [];

if ($filter_status !== '') {
    $where[] = 'status = ?';
    $params[] = $filter_status;
}

if ($filter_type !== '') {
    $where[] = '(employment_type = ? OR agency_name = ?)';
    $params[] = $filter_type;
    $params[] = $filter_type;
}

if ($filter_dept !== '') {
    $where[] = 'dept = ?';
    $params[] = $filter_dept;
}

if ($search_query !== '') {
    $terms = preg_split('/[\s,]+/', $search_query, -1, PREG_SPLIT_NO_EMPTY);
    foreach ($terms as $term) {
        $where[] = '(emp_id LIKE ? OR first_name LIKE ? OR last_name LIKE ?)';
        $t = "%{$term}%";
        array_push($params, $t, $t, $t);
    }
}

$whereSql = 'WHERE ' . implode(' AND ', $where);

// 4. FETCH DATA
$sql = "SELECT * FROM employees {$whereSql} ORDER BY last_name ASC";
$stmt = $pdo->prepare($sql);
$stmt->execute($params);
$employees = $stmt->fetchAll(PDO::FETCH_ASSOC);

// 5. SET HEADERS
$filename = "TESP_Employee_Directory_" . date('Y-m-d') . ".csv";

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');

// 6. OUTPUT DATA
$output = fopen('php://output', 'w');

// Write UTF-8 BOM so Excel opens special characters correctly
fwrite($output, "\xEF\xBB\xBF");

// A. Write Corporate Report Header Block
fputcsv($output, ['TES PHILIPPINES, INC.']);
fputcsv($output, ['MASTER EMPLOYEE DIRECTORY REPORT']);
fputcsv($output, ['Generated On: ' . date('F j, Y, g:i A')]);
fputcsv($output, ['Generated By: ' . ($_SESSION['username'] ?? 'Authorized User')]);
fputcsv($output, ['Total Records: ' . count($employees)]);
fputcsv($output, []); // Blank separator row

// B. Column Headers
$headers = [
    'Employee ID',
    'First Name',
    'Middle Name',
    'Last Name',
    'Gender',
    'Birth Date',
    'Department',
    'Section',
    'Job Title',
    'System Role',
    'Status',
    'Employment Type',
    'Agency Name',
    'Date Hired',
    'Email',
    'Contact Number',
    'Present Address',
    'Permanent Address'
];

if ($includeSensitive) {
    $headers = array_merge($headers, [
        'SSS Number',
        'TIN Number',
        'PhilHealth',
        'Pag-IBIG',
        'Emergency Contact Name',
        'Emergency Contact Number',
        'Emergency Address'
    ]);
}

$headers = array_merge($headers, ['Education', 'Experience', 'Licenses']);
fputcsv($output, $headers);

// C. Write Employee Data Rows
foreach ($employees as $row) {
    $displaySection = $row['section'];
    if (!in_array(strtoupper($row['dept']), ['ADMIN', 'SQP'])) {
        $displaySection = '';
    }

    $rowData = [
        forceExcelText($row['emp_id']),
        sanitizeExcelField($row['first_name']),
        sanitizeExcelField($row['middle_name']),
        sanitizeExcelField($row['last_name']),
        sanitizeExcelField($row['gender']),
        sanitizeExcelField($row['birth_date']),
        sanitizeExcelField($row['dept']),
        sanitizeExcelField($displaySection),
        sanitizeExcelField($row['job_title']),
        sanitizeExcelField($row['system_role']),
        sanitizeExcelField($row['status']),
        sanitizeExcelField($row['employment_type']),
        sanitizeExcelField($row['agency_name']),
        sanitizeExcelField($row['hire_date']),
        sanitizeExcelField($row['email']),
        forceExcelText($row['contact_number']), // Prevents scientific notation (4.26E+18)
        sanitizeExcelField($row['present_address']),
        sanitizeExcelField($row['permanent_address'])
    ];

    if ($includeSensitive) {
        $rowData = array_merge($rowData, [
            forceExcelText(maskSensitive($row['sss_no'])),
            forceExcelText(maskSensitive($row['tin_no'])),
            forceExcelText(maskSensitive($row['philhealth_no'])),
            forceExcelText(maskSensitive($row['pagibig_no'])),
            sanitizeExcelField($row['emergency_name']),
            forceExcelText(maskSensitive($row['emergency_contact'])),
            sanitizeExcelField($row['emergency_address'])
        ]);

        $logger->log(
            $_SESSION['user_id'],
            'EXPORT_EMPLOYEES_SENSITIVE',
            'Exported employee ' . $row['emp_id'] . ' with masked sensitive fields'
        );
    }

    $rowData = array_merge($rowData, [
        sanitizeExcelField($row['education']),
        sanitizeExcelField($row['experience']),
        sanitizeExcelField($row['licenses'])
    ]);

    fputcsv($output, $rowData);
}

fclose($output);
exit;
